#!/usr/bin/env sh

if [[ ! -n $1 ]] || [[ ! -n $2 ]]; then
	echo "frida-ios-dump <source.app> <target.ipa>"
	exit
fi

target_ipa=$(cd "$(dirname "$2")"; pwd)/$(basename "$2")

cd $HOME
if [[ ! -d ".frida-ios-dump" ]]; then
	git clone https://github.com/AloneMonkey/frida-ios-dump.git .frida-ios-dump
fi

cd .frida-ios-dump
pipenv install
pipenv run ./dump.py -o $target_ipa $1